// رابط ثابت مباشرة بدل متغير البيئة
const BASE_URL = 'https://server8.mp3quran.net/maher';

export const surahs = [
  { id: 1, name: 'الفاتحة', englishName: 'Al-Fatiha', frenchName: 'Al-Fatiha', verses: 7 },
  { id: 2, name: 'البقرة', englishName: 'Al-Baqara', frenchName: 'Al-Baqara', verses: 286 },
  { id: 3, name: 'آل عمران', englishName: 'Al-Imran', frenchName: 'Al-Imran', verses: 200 },
  { id: 4, name: 'النساء', englishName: 'An-Nisa', frenchName: 'An-Nisa', verses: 176 },
  { id: 5, name: 'المائدة', englishName: 'Al-Maida', frenchName: 'Al-Maida', verses: 120 },
  { id: 6, name: 'الأنعام', englishName: 'Al-Anam', frenchName: 'Al-Anam', verses: 165 },
  { id: 7, name: 'الأعراف', englishName: 'Al-Araf', frenchName: 'Al-Araf', verses: 206 },
  { id: 8, name: 'الأنفال', englishName: 'Al-Anfal', frenchName: 'Al-Anfal', verses: 75 },
  { id: 9, name: 'التوبة', englishName: 'At-Tawba', frenchName: 'At-Tawba', verses: 129 },
  { id: 10, name: 'يونس', englishName: 'Yunus', frenchName: 'Yunus', verses: 109 },
  { id: 11, name: 'هود', englishName: 'Hud', frenchName: 'Hud', verses: 123 },
  { id: 12, name: 'يوسف', englishName: 'Yusuf', frenchName: 'Yusuf', verses: 111 },
  { id: 13, name: 'الرعد', englishName: 'Ar-Rad', frenchName: 'Ar-Rad', verses: 43 },
  { id: 14, name: 'إبراهيم', englishName: 'Ibrahim', frenchName: 'Ibrahim', verses: 52 },
  { id: 15, name: 'الحجر', englishName: 'Al-Hijr', frenchName: 'Al-Hijr', verses: 99 },
  { id: 16, name: 'النحل', englishName: 'An-Nahl', frenchName: 'An-Nahl', verses: 128 },
  { id: 17, name: 'الإسراء', englishName: 'Al-Isra', frenchName: 'Al-Isra', verses: 111 },
  { id: 18, name: 'الكهف', englishName: 'Al-Kahf', frenchName: 'Al-Kahf', verses: 110 },
  { id: 19, name: 'مريم', englishName: 'Maryam', frenchName: 'Maryam', verses: 98 },
  { id: 20, name: 'طه', englishName: 'Ta-Ha', frenchName: 'Ta-Ha', verses: 135 },
  { id: 21, name: 'الأنبياء', englishName: 'Al-Anbiya', frenchName: 'Al-Anbiya', verses: 112 },
  { id: 22, name: 'الحج', englishName: 'Al-Hajj', frenchName: 'Al-Hajj', verses: 78 },
  { id: 23, name: 'المؤمنون', englishName: 'Al-Muminun', frenchName: 'Al-Muminun', verses: 118 },
  { id: 24, name: 'النور', englishName: 'An-Nur', frenchName: 'An-Nur', verses: 64 },
  { id: 25, name: 'الفرقان', englishName: 'Al-Furqan', frenchName: 'Al-Furqan', verses: 77 },
  { id: 26, name: 'الشعراء', englishName: 'Ash-Shuara', frenchName: 'Ash-Shuara', verses: 227 },
  { id: 27, name: 'النمل', englishName: 'An-Naml', frenchName: 'An-Naml', verses: 93 },
  { id: 28, name: 'القصص', englishName: 'Al-Qasas', frenchName: 'Al-Qasas', verses: 88 },
  { id: 29, name: 'العنكبوت', englishName: 'Al-Ankabut', frenchName: 'Al-Ankabut', verses: 69 },
  { id: 30, name: 'الروم', englishName: 'Ar-Rum', frenchName: 'Ar-Rum', verses: 60 },
  { id: 31, name: 'لقمان', englishName: 'Luqman', frenchName: 'Luqman', verses: 34 },
  { id: 32, name: 'السجدة', englishName: 'As-Sajda', frenchName: 'As-Sajda', verses: 30 },
  { id: 33, name: 'الأحزاب', englishName: 'Al-Ahzab', frenchName: 'Al-Ahzab', verses: 73 },
  { id: 34, name: 'سبأ', englishName: 'Saba', frenchName: 'Saba', verses: 54 },
  { id: 35, name: 'فاطر', englishName: 'Fatir', frenchName: 'Fatir', verses: 45 },
  { id: 36, name: 'يس', englishName: 'Ya-Sin', frenchName: 'Ya-Sin', verses: 83 },
  { id: 37, name: 'الصافات', englishName: 'As-Saffat', frenchName: 'As-Saffat', verses: 182 },
  { id: 38, name: 'ص', englishName: 'Sad', frenchName: 'Sad', verses: 88 },
  { id: 39, name: 'الزمر', englishName: 'Az-Zumar', frenchName: 'Az-Zumar', verses: 75 },
  { id: 40, name: 'غافر', englishName: 'Ghafir', frenchName: 'Ghafir', verses: 85 },
  { id: 41, name: 'فصلت', englishName: 'Fussilat', frenchName: 'Fussilat', verses: 54 },
  { id: 42, name: 'الشورى', englishName: 'Ash-Shura', frenchName: 'Ash-Shura', verses: 53 },
  { id: 43, name: 'الزخرف', englishName: 'Az-Zukhruf', frenchName: 'Az-Zukhruf', verses: 89 },
  { id: 44, name: 'الدخان', englishName: 'Ad-Dukhan', frenchName: 'Ad-Dukhan', verses: 59 },
  { id: 45, name: 'الجاثية', englishName: 'Al-Jathiya', frenchName: 'Al-Jathiya', verses: 37 },
  { id: 46, name: 'الأحقاف', englishName: 'Al-Ahqaf', frenchName: 'Al-Ahqaf', verses: 35 },
  { id: 47, name: 'محمد', englishName: 'Muhammad', frenchName: 'Muhammad', verses: 38 },
  { id: 48, name: 'الفتح', englishName: 'Al-Fath', frenchName: 'Al-Fath', verses: 29 },
  { id: 49, name: 'الحجرات', englishName: 'Al-Hujurat', frenchName: 'Al-Hujurat', verses: 18 },
  { id: 50, name: 'ق', englishName: 'Qaf', frenchName: 'Qaf', verses: 45 },
  { id: 51, name: 'الذاريات', englishName: 'Adh-Dhariyat', frenchName: 'Adh-Dhariyat', verses: 60 },
  { id: 52, name: 'الطور', englishName: 'At-Tur', frenchName: 'At-Tur', verses: 49 },
  { id: 53, name: 'النجم', englishName: 'An-Najm', frenchName: 'An-Najm', verses: 62 },
  { id: 54, name: 'القمر', englishName: 'Al-Qamar', frenchName: 'Al-Qamar', verses: 55 },
  { id: 55, name: 'الرحمن', englishName: 'Ar-Rahman', frenchName: 'Ar-Rahman', verses: 78 },
  { id: 56, name: 'الواقعة', englishName: 'Al-Waqia', frenchName: 'Al-Waqia', verses: 96 },
  { id: 57, name: 'الحديد', englishName: 'Al-Hadid', frenchName: 'Al-Hadid', verses: 29 },
  { id: 58, name: 'المجادلة', englishName: 'Al-Mujadila', frenchName: 'Al-Mujadila', verses: 22 },
  { id: 59, name: 'الحشر', englishName: 'Al-Hashr', frenchName: 'Al-Hashr', verses: 24 },
  { id: 60, name: 'الممتحنة', englishName: 'Al-Mumtahina', frenchName: 'Al-Mumtahina', verses: 13 },
  { id: 61, name: 'الصف', englishName: 'As-Saf', frenchName: 'As-Saf', verses: 14 },
  { id: 62, name: 'الجمعة', englishName: 'Al-Jumua', frenchName: 'Al-Jumua', verses: 11 },
  { id: 63, name: 'المنافقون', englishName: 'Al-Munafiqun', frenchName: 'Al-Munafiqun', verses: 11 },
  { id: 64, name: 'التغابن', englishName: 'At-Taghabun', frenchName: 'At-Taghabun', verses: 18 },
  { id: 65, name: 'الطلاق', englishName: 'At-Talaq', frenchName: 'At-Talaq', verses: 12 },
  { id: 66, name: 'التحريم', englishName: 'At-Tahrim', frenchName: 'At-Tahrim', verses: 12 },
  { id: 67, name: 'الملك', englishName: 'Al-Mulk', frenchName: 'Al-Mulk', verses: 30 },
  { id: 68, name: 'القلم', englishName: 'Al-Qalam', frenchName: 'Al-Qalam', verses: 52 },
  { id: 69, name: 'الحاقة', englishName: 'Al-Haqqah', frenchName: 'Al-Haqqah', verses: 52 },
  { id: 70, name: 'المعارج', englishName: 'Al-Maarij', frenchName: 'Al-Maarij', verses: 44 },
  { id: 71, name: 'نوح', englishName: 'Nuh', frenchName: 'Nuh', verses: 28 },
  { id: 72, name: 'الجن', englishName: 'Al-Jinn', frenchName: 'Al-Jinn', verses: 28 },
  { id: 73, name: 'المزمل', englishName: 'Al-Muzzammil', frenchName: 'Al-Muzzammil', verses: 20 },
  { id: 74, name: 'المدثر', englishName: 'Al-Muddaththir', frenchName: 'Al-Muddaththir', verses: 56 },
  { id: 75, name: 'القيامة', englishName: 'Al-Qiyama', frenchName: 'Al-Qiyama', verses: 40 },
  { id: 76, name: 'الإنسان', englishName: 'Al-Insan', frenchName: 'Al-Insan', verses: 31 },
  { id: 77, name: 'المرسلات', englishName: 'Al-Mursalat', frenchName: 'Al-Mursalat', verses: 50 },
  { id: 78, name: 'النبأ', englishName: 'An-Naba', frenchName: 'An-Naba', verses: 40 },
  { id: 79, name: 'النازعات', englishName: 'An-Naziat', frenchName: 'An-Naziat', verses: 46 },
  { id: 80, name: 'عبس', englishName: 'Abasa', frenchName: 'Abasa', verses: 42 },
  { id: 81, name: 'التكوير', englishName: 'At-Takwir', frenchName: 'At-Takwir', verses: 29 },
  { id: 82, name: 'الانفطار', englishName: 'Al-Infitar', frenchName: 'Al-Infitar', verses: 19 },
  { id: 83, name: 'المطففين', englishName: 'Al-Mutaffifin', frenchName: 'Al-Mutaffifin', verses: 36 },
  { id: 84, name: 'الانشقاق', englishName: 'Al-Inshiqaq', frenchName: 'Al-Inshiqaq', verses: 25 },
  { id: 85, name: 'البروج', englishName: 'Al-Buruj', frenchName: 'Al-Buruj', verses: 22 },
  { id: 86, name: 'الطارق', englishName: 'At-Tariq', frenchName: 'At-Tariq', verses: 17 },
  { id: 87, name: 'الأعلى', englishName: 'Al-Ala', frenchName: 'Al-Ala', verses: 19 },
  { id: 88, name: 'الغاشية', englishName: 'Al-Ghashiya', frenchName: 'Al-Ghashiya', verses: 26 },
  { id: 89, name: 'الفجر', englishName: 'Al-Fajr', frenchName: 'Al-Fajr', verses: 30 },
  { id: 90, name: 'البلد', englishName: 'Al-Balad', frenchName: 'Al-Balad', verses: 20 },
  { id: 91, name: 'الشمس', englishName: 'Ash-Shams', frenchName: 'Ash-Shams', verses: 15 },
  { id: 92, name: 'الليل', englishName: 'Al-Layl', frenchName: 'Al-Layl', verses: 21 },
  { id: 93, name: 'الضحى', englishName: 'Ad-Duha', frenchName: 'Ad-Duha', verses: 11 },
  { id: 94, name: 'الشرح', englishName: 'Ash-Sharh', frenchName: 'Ash-Sharh', verses: 8 },
  { id: 95, name: 'التين', englishName: 'At-Tin', frenchName: 'At-Tin', verses: 8 },
  { id: 96, name: 'العلق', englishName: 'Al-Alaq', frenchName: 'Al-Alaq', verses: 19 },
  { id: 97, name: 'القدر', englishName: 'Al-Qadr', frenchName: 'Al-Qadr', verses: 5 },
  { id: 98, name: 'البينة', englishName: 'Al-Bayyina', frenchName: 'Al-Bayyina', verses: 8 },
  { id: 99, name: 'الزلزلة', englishName: 'Az-Zalzala', frenchName: 'Az-Zalzala', verses: 8 },
  { id: 100, name: 'العاديات', englishName: 'Al-Adiyat', frenchName: 'Al-Adiyat', verses: 11 },
  { id: 101, name: 'القارعة', englishName: 'Al-Qaria', frenchName: 'Al-Qaria', verses: 11 },
  { id: 102, name: 'التكاثر', englishName: 'At-Takathur', frenchName: 'At-Takathur', verses: 8 },
  { id: 103, name: 'العصر', englishName: 'Al-Asr', frenchName: 'Al-Asr', verses: 3 },
  { id: 104, name: 'الهمزة', englishName: 'Al-Humaza', frenchName: 'Al-Humaza', verses: 9 },
  { id: 105, name: 'الفيل', englishName: 'Al-Fil', frenchName: 'Al-Fil', verses: 5 },
  { id: 106, name: 'قريش', englishName: 'Quraysh', frenchName: 'Quraysh', verses: 4 },
  { id: 107, name: 'الماعون', englishName: 'Al-Maun', frenchName: 'Al-Maun', verses: 7 },
  { id: 108, name: 'الكوثر', englishName: 'Al-Kawthar', frenchName: 'Al-Kawthar', verses: 3 },
  { id: 109, name: 'الكافرون', englishName: 'Al-Kafirun', frenchName: 'Al-Kafirun', verses: 6 },
  { id: 110, name: 'النصر', englishName: 'An-Nasr', frenchName: 'An-Nasr', verses: 3 },
  { id: 111, name: 'المسد', englishName: 'Al-Masad', frenchName: 'Al-Masad', verses: 5 },
  { id: 112, name: 'الإخلاص', englishName: 'Al-Ikhlas', frenchName: 'Al-Ikhlas', verses: 4 },
  { id: 113, name: 'الفلق', englishName: 'Al-Falaq', frenchName: 'Al-Falaq', verses: 5 },
  { id: 114, name: 'الناس', englishName: 'An-Nas', frenchName: 'An-Nas', verses: 6 },
];

export const getSurahAudioUrl = (surahId: number): string => {
  const formattedId = String(surahId).padStart(3, '0');
  return `https://ia902802.us.archive.org/28/items/www.elahmad.com_69/${formattedId}.mp3`;
};

export const getSurahById = (id: number) => {
  return surahs.find(surah => surah.id === id);
};