
export const surahPages: Record<number, { name: string; slug: string; pages: number; startPage: number }> = {
  1: { name: 'الفاتحة', slug: 'surah-al-fatiha', pages: 1, startPage: 1 },
  2: { name: 'البقرة', slug: 'surah-al-baqarah', pages: 48, startPage: 2 },
  3: { name: 'آل عمران', slug: 'surah-ali-imran', pages: 27, startPage: 50 },
  4: { name: 'النساء', slug: 'surah-an-nisa', pages: 29, startPage: 77 },
  5: { name: 'المائدة', slug: 'surah-al-maidah', pages: 22, startPage: 106 },
  6: { name: 'الأنعام', slug: 'surah-al-anam', pages: 23, startPage: 128 },
  7: { name: 'الأعراف', slug: 'surah-al-araf', pages: 26, startPage: 151 },
  8: { name: 'الأنفال', slug: 'surah-al-anfal', pages: 10, startPage: 177 },
  9: { name: 'التوبة', slug: 'surah-taubah', pages: 21, startPage: 187 },
  10: { name: 'يونس', slug: 'surah-yunus', pages: 13, startPage: 208 },
  11: { name: 'هود', slug: 'surah-hud', pages: 14, startPage: 221 },
  12: { name: 'يوسف', slug: 'surah-yusuf', pages: 14, startPage: 235 },
  13: { name: 'الرعد', slug: 'surah-rad', pages: 6, startPage: 249 },
  14: { name: 'إبراهيم', slug: 'surah-ibrahim', pages: 7, startPage: 255 },
  15: { name: 'الحجر', slug: 'surah-al-hijr', pages: 5, startPage: 262 },
  16: { name: 'النحل', slug: 'surah-an-nahl', pages: 15, startPage: 267 },
  17: { name: 'الإسراء', slug: 'surah-al-isra', pages: 11, startPage: 282 },
  18: { name: 'الكهف', slug: 'surah-kahf', pages: 12, startPage: 293 },
  19: { name: 'مريم', slug: 'surah-maryam', pages: 7, startPage: 305 },
  20: { name: 'طه', slug: 'surah-taha', pages: 10, startPage: 312 },
  21: { name: 'الأنبياء', slug: 'surah-al-anbiya', pages: 10, startPage: 322 },
  22: { name: 'الحج', slug: 'surah-al-hajj', pages: 10, startPage: 333 },
  23: { name: 'المؤمنون', slug: 'surah-al-muminun', pages: 8, startPage: 342 },
  24: { name: 'النور', slug: 'surah-noor', pages: 9, startPage: 350 },
  25: { name: 'الفرقان', slug: 'surah-furqan', pages: 8, startPage: 359 },
  26: { name: 'الشعراء', slug: 'surah-shura', pages: 10, startPage: 367 },
  27: { name: 'النمل', slug: 'surah-naml', pages: 8, startPage: 377 },
  28: { name: 'القصص', slug: 'surah-al-qasas', pages: 11, startPage: 385 },
  29: { name: 'العنكبوت', slug: 'surah-ankabut', pages: 8, startPage: 396 },
  30: { name: 'الروم', slug: 'surah-ar-rum', pages: 7, startPage: 404 },
  31: { name: 'لقمان', slug: 'surah-luqman', pages: 4, startPage: 411 },
  32: { name: 'السجدة', slug: 'surah-sajdah', pages: 3, startPage: 415 },
  33: { name: 'الأحزاب', slug: 'surah-ahzab', pages: 10, startPage: 418 },
  34: { name: 'سبأ', slug: 'surah-saba', pages: 6, startPage: 428 },
  35: { name: 'فاطر', slug: 'surah-al-fatir', pages: 6, startPage: 434 },
  36: { name: 'يس', slug: 'surah-yaseen', pages: 6, startPage: 440 },
  37: { name: 'الصافات', slug: 'surah-saffat', pages: 7, startPage: 446 },
  38: { name: 'ص', slug: 'surah-sad', pages: 5, startPage: 453 },
  39: { name: 'الزمر', slug: 'surah-zumar', pages: 9, startPage: 458 },
  40: { name: 'غافر', slug: 'surah-ghafar', pages: 10, startPage: 467 },
  41: { name: 'فصلت', slug: 'surah-fussilat', pages: 6, startPage: 477 },
  42: { name: 'الشورى', slug: 'surah-shura', pages: 6, startPage: 483 },
  43: { name: 'الزخرف', slug: 'surah-az-zukhruf', pages: 7, startPage: 489 },
  44: { name: 'الدخان', slug: 'surah-ad-dukhan', pages: 3, startPage: 496 },
  45: { name: 'الجاثية', slug: 'surah-al-jathiyah', pages: 3, startPage: 499 },
  46: { name: 'الأحقاف', slug: 'surah-al-ahqaf', pages: 5, startPage: 502 },
  47: { name: 'محمد', slug: 'surah-muhammad', pages: 4, startPage: 507 },
  48: { name: 'الفتح', slug: 'surah-fatah', pages: 4, startPage: 511 },
  49: { name: 'الحجرات', slug: 'surah-hujurat', pages: 3, startPage: 515 },
  50: { name: 'ق', slug: 'surah-qaf', pages: 2, startPage: 518 },
  51: { name: 'الذاريات', slug: 'surah-adh-dhariyat', pages: 3, startPage: 520 },
  52: { name: 'الطور', slug: 'surah-at-tur', pages: 3, startPage: 523 },
  53: { name: 'النجم', slug: 'surah-najm', pages: 2, startPage: 526 },
  54: { name: 'القمر', slug: 'surah-qamar', pages: 3, startPage: 528 },
  55: { name: 'الرحمن', slug: 'surah-rahman', pages: 3, startPage: 531 },
  56: { name: 'الواقعة', slug: 'surah-waqiah', pages: 3, startPage: 534 },
  57: { name: 'الحديد', slug: 'surah-al-hadid', pages: 5, startPage: 537 },
  58: { name: 'المجادلة', slug: 'surah-al-mujadilah', pages: 3, startPage: 542 },
  59: { name: 'الحشر', slug: 'surah-hashr', pages: 4, startPage: 545 },
  60: { name: 'الممتحنة', slug: 'surah-al-mumtahanah', pages: 2, startPage: 549 },
  61: { name: 'الصف', slug: 'surah-as-saff', pages: 2, startPage: 551 },
  62: { name: 'الجمعة', slug: 'surah-juma', pages: 1, startPage: 553 },
  63: { name: 'المنافقون', slug: 'surah-munafiqun', pages: 2, startPage: 554 },
  64: { name: 'التغابن', slug: 'surah-taghabun', pages: 2, startPage: 556 },
  65: { name: 'الطلاق', slug: 'surah-talaq', pages: 2, startPage: 558 },
  66: { name: 'التحريم', slug: 'surah-tahrim', pages: 2, startPage: 560 },
  67: { name: 'الملك', slug: 'surah-mulk', pages: 2, startPage: 562 },
  68: { name: 'القلم', slug: 'surah-qalam', pages: 2, startPage: 564 },
  69: { name: 'الحاقة', slug: 'surah-al-haqqah', pages: 2, startPage: 566 },
  70: { name: 'المعارج', slug: 'surah-maarij', pages: 2, startPage: 568 },
  71: { name: 'نوح', slug: 'surah-nuh', pages: 2, startPage: 570 },
  72: { name: 'الجن', slug: 'surah-jinn', pages: 2, startPage: 572 },
  73: { name: 'المزمل', slug: 'surah-muzammil', pages: 1, startPage: 574 },
  74: { name: 'المدثر', slug: 'surah-muddathir', pages: 2, startPage: 575 },
  75: { name: 'القيامة', slug: 'surah-al-qiyamah', pages: 1, startPage: 577 },
  76: { name: 'الإنسان', slug: 'surah-al-insan', pages: 2, startPage: 578 },
  77: { name: 'المرسلات', slug: 'surah-mursalat', pages: 2, startPage: 580 },
  78: { name: 'النبأ', slug: 'surah-an-naba', pages: 1, startPage: 582 },
  79: { name: 'النازعات', slug: 'surah-naziat', pages: 2, startPage: 583 },
  80: { name: 'عبس', slug: 'surah-abasa', pages: 1, startPage: 585 },
  81: { name: 'التكوير', slug: 'surah-takwir', pages: 1, startPage: 586 },
  82: { name: 'الانفطار', slug: 'surah-infitar', pages: 1, startPage: 587 },
  83: { name: 'المطففين', slug: 'surah-mutaffifin', pages: 2, startPage: 587 },
  84: { name: 'الانشقاق', slug: 'surah-inshiqaq', pages: 1, startPage: 589 },
  85: { name: 'البروج', slug: 'surah-al-buruj', pages: 1, startPage: 590 },
  86: { name: 'الطارق', slug: 'surah-at-tariq', pages: 1, startPage: 591 },
  87: { name: 'الأعلى', slug: 'surah-al-ala', pages: 1, startPage: 591 },
  88: { name: 'الغاشية', slug: 'surah-ghashiyah', pages: 1, startPage: 592 },
  89: { name: 'الفجر', slug: 'surah-fajr', pages: 1, startPage: 593 },
  90: { name: 'البلد', slug: 'surah-balad', pages: 1, startPage: 594 },
  91: { name: 'الشمس', slug: 'surah-shams', pages: 1, startPage: 595 },
  92: { name: 'الليل', slug: 'surah-lail', pages: 1, startPage: 595 },
  93: { name: 'الضحى', slug: 'surah-duha', pages: 1, startPage: 596 },
  94: { name: 'الشرح', slug: 'surah-alam-nashrah', pages: 1, startPage: 596 },
  95: { name: 'التين', slug: 'surah-at-tin', pages: 1, startPage: 597 },
  96: { name: 'العلق', slug: 'surah-al-alaq', pages: 1, startPage: 597 },
  97: { name: 'القدر', slug: 'surah-qadr', pages: 1, startPage: 598 },
  98: { name: 'البينة', slug: 'surah-al-bayyinah', pages: 1, startPage: 598 },
  99: { name: 'الزلزلة', slug: 'surah-al-zalzalah', pages: 1, startPage: 599 },
  100: { name: 'العاديات', slug: 'surah-al-adiyat', pages: 1, startPage: 599 },
  101: { name: 'القارعة', slug: 'surah-al-qariah', pages: 1, startPage: 600 },
  102: { name: 'التكاثر', slug: 'surah-takathur', pages: 1, startPage: 600 },
  103: { name: 'العصر', slug: 'surah-asr', pages: 1, startPage: 601 },
  104: { name: 'الهمزة', slug: 'surah-humazah', pages: 1, startPage: 601 },
  105: { name: 'الفيل', slug: 'surah-al-fil', pages: 1, startPage: 601 },
  106: { name: 'قريش', slug: 'surah-quraish', pages: 1, startPage: 602 },
  107: { name: 'الماعون', slug: 'surah-al-maun', pages: 1, startPage: 602 },
  108: { name: 'الكوثر', slug: 'surah-kausar', pages: 1, startPage: 602 },
  109: { name: 'الكافرون', slug: 'surah-al-kafirun', pages: 1, startPage: 603 },
  110: { name: 'النصر', slug: 'surah-nasr', pages: 1, startPage: 603 },
  111: { name: 'المسد', slug: 'surah-lahab', pages: 1, startPage: 603 },
  112: { name: 'الإخلاص', slug: 'surah-ikhlas', pages: 1, startPage: 604 },
  113: { name: 'الفلق', slug: 'surah-falaq', pages: 1, startPage: 604 },
  114: { name: 'الناس', slug: 'surah-nas', pages: 1, startPage: 604 },
};

export const getPageUrl = (slug: string, page: number, totalPages: number): string => {
  const base = 'https://salawat.com/images/pages/tajweed';
  if (totalPages === 1) {
    return `${base}/${slug}.jpg`;
  }
  return `${base}/${slug}-${page}.jpg`;
};